#!/bin/sh

INSTDIR="$(dirname $0)"
chroot=$(which chroot)
chrootcmd="env -i TERM=$TERM HOME=$HOME SHELL=/bin/bash $chroot $INSTDIR"

if test x"$1" = "xchroot"; then
	echo "# source /etc/profile"
	$chrootcmd /bin/bash
elif test x"$1" = "xsetup"; then
	shift
	$chrootcmd /setup "$@"
elif test x"$1" = "xfetch"; then
	arch=$(uname -m | sed 's/x86_/amd/')
	getpath=$(wget -O- http://${2:-distfiles.gentoo.org}/releases/$arch/autobuilds/latest-stage3.txt | sed '$!d')
	basepath=$(basename $getpath)
	wget http://${2:-distfiles.gentoo.org}/releases/$arch/autobuilds/$getpath
elif test x"$1" = "xsync"; then
	$chrootcmd /usr/bin/emerge --sync
elif test x"$1" = "xweb-sync"; then
	$chrootcmd /usr/bin/emerge-webrsync
elif test x"$1" = "xhelp"; then
	echo "$0 [prepares mountpoints]"
	echo "$0 setup <...>"
	echo "$0 chroot"
	echo
	echo "$0 fetch <mirror>"
	#echo "$0 unpack"
	#echo "$0 pull"
	echo
	echo "$0 sync"
	echo "$0 web-sync"
else
	mountpoint -q "$INSTDIR"/proc || mount -t proc proc "$INSTDIR"/proc
	mountpoint -q "$INSTDIR"/dev || mount --rbind /dev "$INSTDIR"/dev
	mountpoint -q "$INSTDIR"/sys || mount --rbind /sys "$INSTDIR"/sys

	cmp -s /etc/resolv.conf "$INSTDIR/etc/resolv.conf" || cp -L /etc/resolv.conf $INSTDIR/etc

	echo "# $chrootcmd /bin/bash"
fi

