#!/bin/sh

INSTDIR="$(dirname $0)"
chroot=$(which chroot)
chrootcmd="env -i TERM=$TERM HOME=$HOME SHELL=/bin/bash $chroot $INSTDIR"

if test x"$1" = "xchroot"; then
	echo "# source /etc/profile"
	$chrootcmd /bin/bash
elif test x"$1" = "xsetup"; then
	shift
	$chrootcmd /setup "$@"
elif test x"$1" = "xfetch" || test x"$1" = "xunpack"; then
	pushd "$INSTDIR"
	arch=$(uname -m | sed 's/x86_/amd/')
	getpath=$(wget -O- http://${2:-distfiles.gentoo.org}/releases/$arch/autobuilds/latest-stage3.txt | sed '$!d')
	basepath=$(basename $getpath)
	wget -c http://${2:-distfiles.gentoo.org}/releases/$arch/autobuilds/$getpath
	test x"$1" = "xunpack" && tar xkjpf $basepath -C $INSTDIR
	popd
elif test x"$1" = "xsync"; then
	$chrootcmd /usr/bin/emerge --sync
elif test x"$1" = "xweb-sync"; then
	$chrootcmd /usr/bin/emerge-webrsync
elif test x"$1" = "xprepare"; then
	mountpoint -q "$INSTDIR"/proc || mount -t proc proc "$INSTDIR"/proc
	mountpoint -q "$INSTDIR"/dev || mount --rbind /dev "$INSTDIR"/dev
	mountpoint -q "$INSTDIR"/sys || mount --rbind /sys "$INSTDIR"/sys

	cmp -s /etc/resolv.conf "$INSTDIR/etc/resolv.conf" || cp -L /etc/resolv.conf $INSTDIR/etc
else
	echo -e "$0 prepare\t\tprepare required mountpoints"
	echo -e "$0 setup <...>\t\trun the setup program"
	echo -e "$0 chroot\t\tchroot into your environment"
	echo
	echo -e "$0 fetch <mirror>\tfetch latest stage3 tarball"
	echo -e "$0 unpack <mirror>\tfetch and unpack stage3"
	echo
	echo -e "$0 sync\t\t\tsync portage tree in the chroot"
	echo -e "$0 web-sync\t\tsync portage tree via snapshots"

fi
