#!/bin/sh

set -e

get_uuid() {
	blkid | grep $1 | awk -F\" "{ print \"UUID=\\\"\" \$2 \"\\\"\", \"$2\", \$(NF-1) }"
}

get_fstype() {
	blkid | awk -F\" '{ print $(NF-1) }' | sort -u
}

ckc() {
	config=/usr/share/genkernel/arch/$(uname -m | sed 's/i6/x/')/kernel-config
	if ! egrep -q "^CONFIG_$1=[ym]"; then
		echo echo "CONFIG_$1=y" '>>' $config
	fi
}

# This will fail if /usr/portage has not been prepared
test !-d /usr/portage || (echo /usr/portage not found. Quitting.>&2;exit)
env-update >/dev/null && source /etc/profile

while test "${#@}" -gt 0; do
	case "$1" in
	# do a stage1 install
	-1)	bec="/usr/portage/scripts/bootstrap.sh;"
		bec="$bec emerge -qe system;"
		;;
	-2)	bec="emerge -qe system;"
		;;
	# Set profile to hardened
	-h)	bec="eselect profile set hardened/linux/$(uname -m | sed 's/amd/x86_/;s/i6/x/');"
		for i in gcc libtool binutils linux-headers glibc; do
			bec="$bec emerge -q1 $i;"
		done
		sources="hardened-sources"
		#bec="$bec emerge -qje system;"
		;;
	# open a chrooted shell after installation
	-i)	aac="$aac /bin/sh"
		PS1="(chroot) $PS1"
		;;
	--)	break
		;;
	*)	if test x"$FQDN" = "x"; then
			FQDN=$1
		elif test x"$BOOTPART" = "x"; then
			BOOTPART=$1
		else
			break
		fi
		;;
	esac
	shift
done

test x"$FQDN" = "x" && read -e -p "Hostname: " FQDN
test x"$BOOTPART" = "x" && read -e -p "Boot Partition: " BOOTPART

passwd

HOSTNAME="$(echo $FQDN | awk -F. '{print $1}')"
# The following awk script could be simplified to:
#	{ print $(NF-1) "." $NF }
# However, if you change the '(NF-1)' below to '2', you just chop off
# the first part (if you have deeper hostnames and more robust mail)
DOMAIN="$(echo $FQDN | awk -F. '{ for(i=(NF-1); i<NF; i++) { printf("%s.", $i) } print $NF }')"

cat >/etc/conf.d/hostname <<EOF
hostname="$HOSTNAME"
EOF

cat >/etc/hosts <<EOF
127.0.0.1 $FQDN $HOSTNAME localhost
::1 $FQDN $HOSTNAME localhost
EOF

# blkid is part of e2fsprogs and should be in system
aec="$aec $(ckc RTC);"
for i in $(get_fstype); do
	case "$i" in
	crypto_LUKS)	fsprogs="$fsprogs cryptsetup"
			gkopts="$gkopts --luks --menuconfig"
			packageuse=/etc/portage/package.use
			if test -f $packageuse; then
				cat >>$packageuse<<-EOF
				dev-libs/popt static-libs
				dev-libs/libgcrypt static-libs
				dev-libs/libgpg-error static-libs
				sys-apps/util-linux static-libs
				EOF
			else
				test -d $packageuse || mkdir -p $packageuse
				echo dev-libs/popt static-libs>>$packageuse/dev-libs
				echo dev-libs/libgcrypt static-libs>>$packageuse/dev-libs
				echo dev-libs/libgpg-error static-libs>>$packageuse/dev-libs
				echo sys-apps/util-linux static-libs>>$packageuse/sys-apps
			fi
			;;
	LVM2_member)	fsprogs="$fsprogs lvm2"
			gkopts="$gkopts --lvm"
			aec="$aec rc-update add lvm boot;"
			;;
	btrfs)	fsprogs="$fsprogs btrfs-progs"
		# as part of this overlay, btrfs-progs is unmasked
		aec="$aec $(ckc BTRFS_FS);"
		# btrfs needs to be enabled in the kernel
		;;
	xfs)	fsprogs="$fsprogs xfsprogs"
		;;
	# XXX: the following are untested and need capitalisation checks
	reiserfs)	fsprogs="$fsprogs reiserfsprogs"
			;;
	jfs)	fsprogs="$fsprogs jfsutils"
		;;
	*raid*)	fsprogs="$fsprogs mdadm"
		gkopts="$gkopts --mdadm"
		aec="$aec rc-update add mdraid boot;"
		;;
	fat*)	fsprogs="$fsprogs dosfstools"
		;;
	ntfs)	fsprogs="$fsprogs ntfs3g"
		;;
	ext*)	;; # nothing needs to be done
	*)	;; # unknown entry
	esac
done

test x"$bec" = "x" || sh -c "$bec"

test	"$(sha256sum /etc/localtime              | awk '{print $1}')" = \
	"$(sha256sum /usr/share/zoneinfo/Factory | awk '{print $1}')"   \
		&& emerge -1q timezone-data
emerge -q ${sources:-gentoo-sources} genkernel \
	grub:2 $fsprogs \
	msmtp vixie-cron syslog-ng dhcpcd \
	ntp nfs-utils acpid iproute2

cat >>/etc/msmtprc <<EOF
maildomain $FQDN
host $DOMAIN
domain $DOMAIN
EOF

cat >>/etc/fstab <<EOF
$(get_uuid $BOOTPART /boot) noatime,noauto 1 2
$(get_uuid $(grub2-probe -t device /) /) noatime 1 1
EOF

test x"$aec" = "x" || sh -c "$aec"

genkernel $gkopts "$@" all
grub2-install /dev/sda
grub2-mkconfig -o /boot/grub2/grub.cfg

eselect news read

test x"$aac" = "x" || sh -c "$aac"
