#!/bin/sh

set -e

# This will fail if /usr/portage has not been prepared
env-update && source /etc/profile

while true; do
	case "$1" in
	--)	shift; break
		;;
	*)	if test x"$NEWHOST" = "x"; then
			NEWHOST=$1
		elif test x"$BOOTPART" = "x"; then
			BOOTPART=$1
		else
			break
		fi
		shift
		;;
	esac
done

test x"$NEWHOST" = "x" && read -e -p "Hostname: " NEWHOST
test x"$BOOTPART" = "x" && read -e -p "Boot Partition: " BOOTPART

passwd


cat >/etc/hostname <<EOF
hostname="$(echo $NEWHOST | awk -F. '{print $1}')"
EOF

cat >/etc/hosts <<EOF
127.0.0.1 $NEWHOST $(echo $NEWHOST | awk -F. '{print $1}') localhost
::1 $NEWHOST $(echo $NEWHOST | awk -F. '{print $1}') localhost
EOF

# The following awk scripts could be simplified to:
#	{ x=NF-1; print $x "." $NF }
# However, if you change the '(NF-1)' below to '2', you just chop off
# the first part (if you have deeper hostnames and more robust mail)
cat >>/etc/msmtprc <<EOF
maildomain $NEWHOST
host $(echo $NEWHOST | awk -F. '{ for(i=(NF-1); i<NF; i++) { printf("%s.", $i) } print $NF }')
domain $(echo $NEWHOST | awk -F. '{ for(i=(NF-1); i<NF; i++) { printf("%s.", $i) } print $NF }')
EOF

cat >>/etc/fstab <<EOF
$(blkid | grep $BOOTPART | awk -F\" '{ print "UUID=\"" $2 "\"", "/boot", $3 }') noatime,noauto 1 2
EOF

# blkid is part of e2fsprogs and should be in system
for i in $(blkid | awk -F\" '{print $(NF-1)}' | sort -u); do
	case "$i" in
	crypto_LUKS)	fsprogs="$fsprogs cryptsetup"
			gkopts="$gkopts --luks"
			;;
	LVM2_member)	fsprogs="$fsprogs lvm2"
			gkopts="$gkopts --lvm"
			;;
	btrfs)	fsprogs="$fsprogs btrfs-progs"
		;; # as part of this overlay, btrfs-progs is unmasked
	xfs)	fsprogs="$fsprogs xfsprogs"
		;;
	# XXX: the following are untested and need capitalisation checks
	reiserfs)	fsprogs="$fsprogs reiserfsprogs"
			;;
	jfs)	fsprogs="$fsprogs jfsutils"
		;;
	*raid*)	fsprogs="$fsprogs mdadm"
		gkopts="$gkopts --mdadm"
		;;
	ext*)	;; # nothing needs to be done
	*)	;; # unknown entry
	esac
done

emerge -1 timezone-data
emerge -qkj gentoo-sources genkernel \
	grub:2 $fsprogs \
	msmtp vixie-cron syslog-ng dhcpcd ntp

genkernel $gkopts "$@" all
grub2-install /dev/sda
cat >>/etc/fstab <<EOF
$(blkid | grep $(grub2-probe -t device /) | awk -F\" '{ print "UUID=\"" $2 "\"", "/", $3 }') noatime,compress 1 1
EOF
grub2-mkconfig -o /boot/grub2/grub.cfg

